# .scrutinizer.yml
build:
    environment:
        php: 7.0.6
    dependencies:
        before:
            - 'composer require --dev --prefer-source typo3/cms="^8.6.0"'

checks:
    php: true

filter:
    dependency_paths:
        - Contrib/
    excluded_paths:
        - ".build/"
