# .travis.yml
language: php

branches:
  only:
    - master
    - BP_7-0
    - BP_6-2

php:
  - 5.5
  - 5.6
  - 7.0

env:
  - TYPO3_VERSION=^7.6.0
  - TYPO3_VERSION=dev-master

matrix:
  allow_failures:
    - env: TYPO3_VERSION=dev-master
  exclude:
    - php: 5.5
      env: TYPO3_VERSION=dev-master
    - php: 5.6
      env: TYPO3_VERSION=dev-master

sudo: false

addons:
  apt:
    packages:
      - parallel

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - phpenv config-rm xdebug.ini
  - composer self-update
  - composer --version
  - if [ "$GITHUB_COMPOSER_AUTH" ]; then composer config -g github-oauth.github.com $GITHUB_COMPOSER_AUTH; fi

before_script:
  - composer require typo3/cms=$TYPO3_VERSION
  - export TYPO3_PATH_WEB="$PWD/.build/web"

script:
  - >
    echo;
    echo "Running unit tests";
    .Build/bin/phpunit --colors -c .build/vendor/typo3/cms/typo3/sysext/core/Build/UnitTests.xml
  - >
    echo;
    echo "Running php lint";
    find . -name \*.php ! -path "./.build/*" | parallel --gnu php -d display_errors=stderr -l {} > /dev/null \;
  - >
    echo;
    echo "Running phpcs";
    .build/bin/phpcs --standard=PSR2 -n Classes/
  - >
    echo "Installing npm modules";
    pushd Build;
    npm install && npm install bower grunt-cli;
    echo "Installing bower dependencies";
    node_modules/.bin/bower install;
    echo "Executing grunt";
    node_modules/.bin/grunt;
    popd
